       -----------WEEK 1 - Day 4-----------
                      - Manojkiran G

## NumPy

- NumPy, short for "Numerical Python," is a powerful library in Python that provides support for large, multi-dimensional arrays and matrices, along with a collection of mathematical functions to operate on these arrays. 
- It is a fundamental tool for numerical and scientific computing in Python, offering efficient data structures for handling numerical operations and providing a foundation for many other scientific libraries and applications.
- In data science, NumPy is a fundamental library that plays a crucial role due to its array-based computing and mathematical functions.

#### Import NumPy

In [34]:
import numpy as np

#### Creating NumPy Arrays

In [35]:
# Creating a 1D array
my_array = np.array([1, 2, 3, 4, 5])

print("1D Array:")
print(my_array)

1D Array:
[1 2 3 4 5]


In [36]:
# Creating a 2D array
my_2d_array = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

print("2D Array:")
print(my_2d_array)

2D Array:
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [37]:
# Creating a 3D array
my_3d_array = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

print("3D Array:")
print(my_3d_array)

3D Array:
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


#### Array Dimension ,Shapes and Size

- Using the ndim , shape and size attributes the dimension , shape and size of an array could be obtained

In [38]:
# Creating arrays of different dimensions
array_1d = np.array([1, 2, 3, 4, 5])
array_2d = np.array([[1, 2, 3], [4, 5, 6]])
array_3d = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])

# Checking dimensions,shape and size
print("Array 1D:")
print("Dimensions:", array_1d.ndim)
print("Shape:", array_1d.shape)
print("Size:",array_1d.size)

print("\nArray 2D:")
print("Dimensions:", array_2d.ndim)
print("Shape:", array_2d.shape)
print("Size:",array_2d.size)

print("\nArray 3D:")
print("Dimensions:", array_3d.ndim)
print("Shape:", array_3d.shape)
print("Size:",array_3d.size)

Array 1D:
Dimensions: 1
Shape: (5,)
Size: 5

Array 2D:
Dimensions: 2
Shape: (2, 3)
Size: 6

Array 3D:
Dimensions: 3
Shape: (2, 2, 2)
Size: 8


#### Indexing 

In [39]:
my_array = np.array([[1, 2, 3], [4, 5, 6]])

# Accessing elements using indexing
element_2_1 = my_2d_array[1, 0]

print("Element at position (2, 1):", element_2_1)

Element at position (2, 1): 4


#### Slicing
- Array slicing in NumPy allows you to create views on the original array by extracting a portion of it. 

In [40]:
my_array = np.array([10, 20, 30, 40, 50])

# Slicing the array
sliced_array = my_array[1:4]  # Elements from index 1 to 3

print("Original Array:", my_array)
print("Sliced Array:", sliced_array)

Original Array: [10 20 30 40 50]
Sliced Array: [20 30 40]


In [41]:
my_2d_array = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

# Slicing the 2D array
sliced_2d_array = my_2d_array[0:2, 1:3]  # Rows 0 to 1, Columns 1 to 2

print("Original 2D Array:",my_2d_array)
print("\nSliced 2D Array:",sliced_2d_array)

Original 2D Array: [[1 2 3]
 [4 5 6]
 [7 8 9]]

Sliced 2D Array: [[2 3]
 [5 6]]


#### Element-wise Operations

**1d array**

In [42]:
array1 = np.array([1, 2, 3, 4, 5])
array2 = np.array([10, 20, 30, 40, 50])

# Element-wise addition
result_addition = array1 + array2

# Element-wise multiplication
result_multiplication = array1 * array2

print("Element-wise Addition:", result_addition)
print("Element-wise Multiplication:", result_multiplication)

Element-wise Addition: [11 22 33 44 55]
Element-wise Multiplication: [ 10  40  90 160 250]


**2d array**

In [44]:
matrix1 = np.array([[2, 3], [1, 4]])
matrix2 = np.array([[5, 1], [2, 2]])

# Element-wise multiplication
elementwise_result = matrix1 * matrix2

# Matrix multiplication
matrix_result = np.dot(matrix1, matrix2)

print("\nElement-wise Multiplication:",elementwise_result)

print("\nMatrix Multiplication:",matrix_result)


Element-wise Multiplication: [[10  3]
 [ 2  8]]

Matrix Multiplication: [[16  8]
 [13  9]]


#### Append and Delete

- In NumPy,np.append is used to add elements to an array, and np.delete to remove elements.

**1d array**

In [45]:
original_array = np.array([10, 20, 30, 40, 50])

appended_array = np.append(original_array, 60)

print("Appended Array:", appended_array)

Appended Array: [10 20 30 40 50 60]


In [46]:
original_array = np.array([10, 20, 30, 40, 50])

deleted_array = np.delete(original_array, 1)  #Remove the item at index 1 (value 20)

print("\nArray after Deletion:",deleted_array)


Array after Deletion: [10 30 40 50]


**2d array**

In [47]:
original_array = np.array([[1, 2, 3], [4, 5, 6]])

new_row = np.array([[7, 8, 9]])
appended_array = np.append(original_array, new_row, axis=0)

deleted_row_array = np.delete(appended_array, 1, axis=0)

print("\nAppended Array:",appended_array)

print("\nArray after deleting a row:",deleted_row_array)


Appended Array: [[1 2 3]
 [4 5 6]
 [7 8 9]]

Array after deleting a row: [[1 2 3]
 [7 8 9]]


#### Aggregation Functions and Universal Functions

- NumPy provides various aggregation functions (also known as reduction functions) and universal functions (ufuncs) for performing operations on arrays.

In [48]:
my_array = np.array([10, 5, 8, 15, 7])

# Aggregation Functions
print("Sum:", np.sum(my_array))
print("Mean:", np.mean(my_array))
print("Minimum:", np.min(my_array))
print("Maximum:", np.max(my_array))

Sum: 45
Mean: 9.0
Minimum: 5
Maximum: 15


In [49]:
# Universal Functions (ufuncs)
print("\nSquare Root:", np.sqrt(my_array))
print("Exponential (e^x):", np.exp(my_array))
print("Element-wise Sine:", np.sin(my_array))


Square Root: [3.16227766 2.23606798 2.82842712 3.87298335 2.64575131]
Exponential (e^x): [2.20264658e+04 1.48413159e+02 2.98095799e+03 3.26901737e+06
 1.09663316e+03]
Element-wise Sine: [-0.54402111 -0.95892427  0.98935825  0.65028784  0.6569866 ]


#### Reshaping arrays 

- Reshaping arrays in NumPy involves changing the shape (dimensions) of the array while preserving the total number of elements. 
- .reshape function is used to reshape the arrays

In [50]:
original_array = np.array([1, 2, 3, 4, 5, 6])

# Reshaping to a 2D array (2 rows, 3 columns)
reshaped_array_2d = original_array.reshape(2, 3)

print("Original Array:",original_array)

print("\nReshaped 2D Array:",reshaped_array_2d)

Original Array: [1 2 3 4 5 6]

Reshaped 2D Array: [[1 2 3]
 [4 5 6]]


#### Combining Arrays

- NumPy provides functions such as np.concatenate to combine arrays

In [51]:
array1 = np.array([1, 2, 3])
array2 = np.array([4, 5, 6])

combined_array = np.concatenate((array1, array2), axis=0)

print("\nCombined Array:", combined_array)


Combined Array: [1 2 3 4 5 6]


- NumPy provides several functions for combining arrays, and one of them is np.vstack for vertical stacking and np.hstack for horizontal stacking. 

In [52]:
array1 = np.array([10, 20, 30])
array2 = np.array([40, 50, 60])

# Vertical stacking (combining along rows)
vertical_stack = np.vstack((array1, array2))

# Horizontal stacking (combining along columns)
horizontal_stack = np.hstack((array1, array2))

print("\nVertical Stack:",vertical_stack)

print("\nHorizontal Stack:",horizontal_stack)


Vertical Stack: [[10 20 30]
 [40 50 60]]

Horizontal Stack: [10 20 30 40 50 60]


#### Splitting Arrays

- NumPy provides functions for splitting arrays, such as np.split for equal division along a specified axis. 

In [53]:
arr = np.array([100, 200, 300, 400, 500, 600,700,800])

# Split into 4 equal parts
split_arr = np.split(arr, 4)
split_arr

[array([100, 200]), array([300, 400]), array([500, 600]), array([700, 800])]

#### Sorting Numpy Arrays

- NumPy provides the np.sort function for sorting arrays

In [54]:
original_array = np.array([4, 2, 7, 1, 9, 5])

# Sorting the array
sorted_array = np.sort(original_array)

print("\nSorted Array:")
print(sorted_array)


Sorted Array:
[1 2 4 5 7 9]
