      -----------WEEK 1 - Day 5-----------
                    - Manojkiran G

## NumPy Continuation

In [1]:
import numpy as np

**Filter in NumPy**

In [2]:
arr = np.array([41, 40, 42, 43, 44])

x = [True, True, False, True, False]

newarr = arr[x]

print(newarr)

[41 40 43]


**Identify Missing Values**

- NumPy provides a function called numpy.isnan() to identify missing (NaN) values in arrays. 

In [3]:
array_with_nan = np.array([1.0, np.nan, 3.0, 4.0, 5.0, np.nan, 7.0])

# Identifying missing values
missing_values = np.isnan(array_with_nan)

print("Original Array:",array_with_nan)

print("\nMissing Values:",missing_values)

Original Array: [ 1. nan  3.  4.  5. nan  7.]

Missing Values: [False  True False False False  True False]


**Removing rows or columns with Missing Values**

- Using boolean indexing to filter out rows or columns containing missing values.

In [4]:
array_with_nan = np.array([[1, 2, np.nan],
                           [4, 5, 6],
                           [7, np.nan, 9]])

# Removing columns with missing values
cleaned_array = array_with_nan[:, ~np.any(np.isnan(array_with_nan), axis=0)]

print("Original Array with NaN:",array_with_nan)

print("\nArray after removing rows with NaN:",cleaned_array)

Original Array with NaN: [[ 1.  2. nan]
 [ 4.  5.  6.]
 [ 7. nan  9.]]

Array after removing rows with NaN: [[1.]
 [4.]
 [7.]]


#### Data Transformation 

Data transformation in NumPy typically involves applying various mathematical operations or functions to the elements of an array to achieve a specific goal. 

In [5]:
original_array = np.array([1, 2, 3, 4, 5])

# Standardization (Z-score normalization)
mean_value = np.mean(original_array)
std_deviation = np.std(original_array)
standardized_array = (original_array - mean_value) / std_deviation

# Logarithmic transformation
log_transformed_array = np.log(original_array)

print("Original Array:",original_array)

print("\nStandardized Array:",standardized_array)

print("\nLog-Transformed Array:",log_transformed_array)

Original Array: [1 2 3 4 5]

Standardized Array: [-1.41421356 -0.70710678  0.          0.70710678  1.41421356]

Log-Transformed Array: [0.         0.69314718 1.09861229 1.38629436 1.60943791]


#### Searching

- Searching is an operation or a technique that helps finds the place of a given element or value in the list.
- Any search is said to be successful or unsuccessful depending upon whether the element that is being searched is found or not.

- **numpy.argmax() :**

This function returns indices of the max element of the array in a particular axis.

In [6]:
arr = np.arange(9).reshape(3, 3)
print("\nMax element : ", np.argmax(arr))


Max element :  8


- **numpy.nanargmax() :**

This function returns indices of the max element of the array in a particular axis ignoring NaNs.

The results cannot be trusted if a slice contains only NaNs and Infs.

In [7]:
arr2 = np.array([[np.nan, 5], [1, 7]])
print((np.nanargmax(arr2)))
 
print(( np.nanargmax(arr2, axis = 1)))

3
[1 1]


- **numpy.argmin() :**

This function returns the indices of the minimum values along an axis.

In [8]:
array = np.arange(10)

print(np.argmin(array, axis=0))

0


#### Counting

- **numpy.count_nonzero() :**

Counts the number of non-zero values in the array.

In [9]:
a = np.count_nonzero([[1,1,7,0,0],[5,1,0,4,10]])
b = np.count_nonzero([[10,1,8,0,0],[3,4,0,0,11]])
 
print("Number of nonzero values is :",a)
print("Number of nonzero values is :",b)

Number of nonzero values is : 7
Number of nonzero values is : 6


- **numpy.nonzero():**

Return the indices of the elements that are non-zero.

In [10]:
a = np.array([[10,1,4,0,0],[0,0,0,4,11]])
print(np.nonzero(a))

(array([0, 0, 0, 1, 1], dtype=int64), array([0, 1, 2, 3, 4], dtype=int64))


- **numpy.flatnonzero():**

Return indices that are non-zero in the flattened version of a.

In [11]:
a = np.array([[0,1,8,0,0],[5,4,0,0,11]])
print(np.flatnonzero(a))

[1 2 5 6 9]


- **numpy.extract():**

The extract() function returns the elements satisfying any condition.

In [12]:
x = np.arange(9.).reshape(3, 3)
condition = np.mod(x,2) == 0

print(np.extract(condition, x))

[0. 2. 4. 6. 8.]


- **numpy.where() function:**

This function is used to return the indices of all the elements which satisfies a particular condition.

In [13]:
arr = np.array([3, 12, 5, 56, 8, 3, 13, 77, 5])
print(np.where(arr>10))

(array([1, 3, 6, 7], dtype=int64),)


#### Random Generation Function

**Importing random Module**

- Python random module is a built-in module for random numbers in Python.

- These are sort of fake random numbers which do not possess True randomness.

In [14]:
import random

NumPy provides the np.random.choice function for simple random sampling.

**1.random.choice**

In [15]:
original_array = np.array([10, 20, 30, 40, 50, 60, 70, 80, 90, 100])

sampled_array = np.random.choice(original_array, size=5, replace=False)

print("Original Array:",original_array)

print("\nSampled Array:",sampled_array)

Original Array: [ 10  20  30  40  50  60  70  80  90 100]

Sampled Array: [ 90 100  10  30  60]


**2. rand():** 

- Return 1-D array with random values between 0 to 1, can provide (x,y) args to shape the array to form multi-dim array.

In [16]:
a = np.random.rand(15)
print(a)

b = np.random.rand(4, 4)
print(b)

[0.12509818 0.63586094 0.40440931 0.85996317 0.85890913 0.77217396
 0.74774883 0.95511709 0.12934298 0.72875921 0.44489558 0.26915671
 0.39494791 0.16095991 0.16600784]
[[0.83590876 0.50801235 0.57524722 0.01172726]
 [0.30870167 0.83057593 0.88207748 0.69243181]
 [0.7206736  0.73770392 0.7720823  0.87422605]
 [0.30790914 0.31389117 0.8513448  0.54726921]]


**3. ranf():**

- Generate random nums between 0 to 1.
- Takes only 1 arg.

In [17]:
a = np.random.ranf(6)
print(a)

[0.64677889 0.20406274 0.88841616 0.72961149 0.31441693 0.41078246]


**4. randint():**

- Generate random int numbers.
- Syntax - np.random.randint(low, high[None by default], size[None by default], dtype='i')

In [18]:
a = np.random.randint(3,5,5,dtype='i')
print(a)

b = np.random.randint(3,15)
print(b)

[3 3 4 3 3]
7


**5. randn():**

- Generate the normally distributed numbers around (0,0) i.e. Origin co-ordinates.
- Syntax - np.random.randn(num)
- Return 1-D array.

In [19]:
random_samples = np.random.randn(5)

print("Random Samples from Standard Normal Distribution:",random_samples)

Random Samples from Standard Normal Distribution: [ 0.78619172 -0.35313619 -0.90233497  0.42180261  0.69318769]


**6.random.binomial**

- The numpy.random.binomial function is used to generate samples from a binomial distribution.

In [20]:
n_trials = 10
probability = 0.4
binomial_values = np.random.binomial(n_trials, probability, 3)
print(binomial_values)

[4 5 4]


**6.random.multinomial**

- The numpy.random.multinomial function is used to draw samples from a multinomial distribution.
- A multinomial distribution is a generalization of the binomial distribution to more than two categories. 

In [21]:
n_trials = 10
probabilities = [0.2, 0.3, 0.4, 0.5] 
multinomial_values = np.random.multinomial(n_trials, probabilities, 5)
print(multinomial_values)

[[2 3 4 1]
 [0 6 3 1]
 [0 6 2 2]
 [5 2 3 0]
 [3 5 2 0]]


**7.random.exponential**

- The numpy.random.exponential function is used to generate random samples from an exponential distribution. 

In [23]:
scale_parameter = 0.5
exponential_values = np.random.exponential(scale_parameter, 3)
print(exponential_values)

[0.3655058 0.3378744 0.938466 ]


**8.random.poisson**

- The numpy.random.poisson function is used to generate random samples from a Poisson distribution. 

In [24]:
rate = 5.0
poisson_values = np.random.poisson(rate, 3)
print(poisson_values)

[6 6 4]


**9.random.lognormal**

- The numpy.random.lognormal function is used to generate random samples from a log-normal distribution. 

In [25]:
mean_of_log = 0
std_dev_of_log = 1
lognormal_values = np.random.lognormal(mean_of_log, std_dev_of_log, 3)
print(lognormal_values)

[1.93086584 0.39942786 0.21886726]


#### Complex Matrix Operations

- **Creating Complex Matrices:**

In [26]:
complex_matrix = np.array([[1 + 2j, 3 - 1j], [4j, 5]])
print("Complex Matrix:",complex_matrix)

Complex Matrix: [[1.+2.j 3.-1.j]
 [0.+4.j 5.+0.j]]


- **Complex Conjugate:**


In [27]:
conjugate_matrix = np.conjugate(complex_matrix)
print("\nComplex Conjugate:",conjugate_matrix)


Complex Conjugate: [[1.-2.j 3.+1.j]
 [0.-4.j 5.-0.j]]


- **Real and Imaginary Parts:**

In [28]:
real_part = np.real(complex_matrix)
imaginary_part = np.imag(complex_matrix)
print("\nReal Part:",real_part)
print("\nImaginary Part:",imaginary_part)


Real Part: [[1. 3.]
 [0. 5.]]

Imaginary Part: [[ 2. -1.]
 [ 4.  0.]]


- **Eigenvalues and Eigenvectors:**

In [29]:
eigenvalues, eigenvectors = np.linalg.eig(complex_matrix)
print("\nEigenvalues:",eigenvalues)
print("\nEigenvectors:",eigenvectors)


Eigenvalues: [0.03098115-0.34724642j 5.96901885+2.34724642j]

Eigenvectors: [[ 0.77971523+0.j          0.49540959-0.20452102j]
 [-0.04364925-0.62461101j  0.84423959+0.j        ]]


- **Inverse**

In [30]:
inverse_matrix = np.linalg.inv(complex_matrix)
print(inverse_matrix)

[[ 1. +2.j  -1. -1.j ]
 [ 1.6-0.8j -0.6+0.8j]]


 ### NumPy advanced techniques

**NumPy FFT (Fast Fourier Transform):**

- NumPy includes functions for computing the FFT, facilitating frequency domain analysis.

In [31]:
signal = np.array([1, 2, 3, 4])
fft_result = np.fft.fft(signal)
print(fft_result)

[10.+0.j -2.+2.j -2.+0.j -2.-2.j]


**NumPy Memory Views:**

- NumPy's np.ndarray provides an interface for memory views, allowing efficient sharing of memory between arrays.

In [32]:
array = np.array([1, 2, 3, 4, 5])
memory_view = array[2:5].data
print(memory_view)

**Masking in NumPy**

- Masking in NumPy involves creating a boolean array (mask) based on a certain condition and then using this mask to filter elements from an array. 

In [33]:
original_array = np.array([1, 2, 3, 4, 5, 6])

# Creating a mask based on a condition
mask = original_array > 3

# Applying the mask to filter elements
masked_array = original_array[mask]

print("Original Array:",original_array)

print("\nMasked Array (elements greater than 3):",masked_array)

Original Array: [1 2 3 4 5 6]

Masked Array (elements greater than 3): [4 5 6]


**Broadcasting in NumPy**

- Broadcasting in NumPy allows for arithmetic operations on arrays of different shapes and sizes without the need for explicit loops or creating new arrays.

In [34]:
array1 = np.array([[1, 2, 3], [4, 5, 6]])

scalar = np.array([10, 20, 30])

# Broadcasting the 1D array to the 2D array
result_array = array1 + scalar

print("Array 1:",array1)

print("\nScalar:",scalar)

print("\nResult after Broadcasting:",result_array)

Array 1: [[1 2 3]
 [4 5 6]]

Scalar: [10 20 30]

Result after Broadcasting: [[11 22 33]
 [14 25 36]]


**Fancy Indexing in NumPy**

- Fancy indexing in NumPy refers to using arrays of indices to access or modify elements from another array. 

In [35]:
original_array = np.array([10, 20, 30, 40, 50])

indices = np.array([1, 3, 4])

# Using fancy indexing to access elements
selected_elements = original_array[indices]

# Modifying elements
original_array[indices] = 99

print("Original Array:",original_array)

print("\nSelected Elements using Fancy Indexing:",selected_elements)

Original Array: [10 99 30 99 99]

Selected Elements using Fancy Indexing: [20 40 50]


**Structured arrays**

- Structured arrays in NumPy allow you to define custom data types and create arrays with multiple fields.

In [36]:
data_type = [('name', 'U10'), ('age', int)]
people_data = np.array([('Jack', 25), ('Alex', 30), ('Billy', 22)], dtype=data_type)

# Accessing fields of the structured array
names = people_data['name']
ages = people_data['age']

print("Structured Array:",people_data)

print("\nNames:",names)

print("\nAges:",ages) 

#Accessing
print('\n'+ people_data['name'][0])
print(people_data['age'][2])

Structured Array: [('Jack', 25) ('Alex', 30) ('Billy', 22)]

Names: ['Jack' 'Alex' 'Billy']

Ages: [25 30 22]

Jack
22
